title: "Object‑oriented programming course"
baseurl: "/object-oriented-programming"
url: "https://maryshev3.github.io"

# Jekyll
markdown: kramdown
highlighter: rouge

# Тема
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-remote-theme

# Коллекция страниц
collections:
  pages:
    output: true
    permalink: /:path/

# Дефолты для ru/en
defaults:
  - scope:
      path: "_pages/ru"
    values:
      layout: default
      lang: "ru"
  - scope:
      path: "_pages/en"
    values:
      layout: default
      lang: "en"